### ISSUE TITLE
Customized splash messages 

### ISSUE THREAD

**Issue by FrederoxGit** [FrederoxGit/Cosmos#8]

**Comment by outercloudstudio** [comment]
What do you mean by customized splash images?

**Comment by FrederoxGit** [comment]
Splash messages are the yellow text on the title screen, while not really a feature that effects gameplay, i think it'd be a nice touch

**Comment by FrederoxGit** [comment]
RP/splashes.json
```
{
  "splashes": [
    "Example message!"
  ]
}
```

**Comment by outercloudstudio** [comment]
I see. Unfortunately I have no idea how to add those.

**Comment by FrederoxGit** [comment]
> RP/splashes.json
> ```
> {
>   "splashes": [
>     "Example message!"
>   ]
> }
> ```

In RP/splashes.json

You can define an array called "splashes" each item in the array is a different splash text, as shown above in this code snippet

**Comment by outercloudstudio** [comment]
I see. I'll add some splashes when I get done with school.
